name: JavaScript Hello Action
on: push

jobs:
  JavaScriptHello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      # - name: JS Private Hello Action
      #   uses: ./.github/actions/hello
      #   id: hello
      #   with:
      #     who-to-greet: "world"

      - name: JS Public Hello Action
        uses: LeeTann/github-actions-open-issue@v1
        id: hello
        with:
          who-to-greet: "My Public Custom World"

      - name: Echo Hello
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
