name: Container
on: push

jobs:
  Docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:14.18-buster
    steps:
      - name: Log Node Version
        run: node -

      - name: Step with Docker
        uses: docker://node:16.10.0-alpine3.14
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"

      - name: Log Node Verion with Docker
        uses: docker://node:16.10.0-alpine3.14
        with:
          entrypoint: /usr/local/bin/node
          args: -v

  Node-Docker:
    runs-on: ubuntu-latest
    container:
      image: node:16.10.0-alpine3.14
    steps:
      - name: Log Node Version
        run: |
          node -v
          cat /etc/os-release
