name: Actions Workflow

on: [push]

jobs:
  RunGithubActions:
    runs-on: ubuntu-latest

    steps:
      - name: List Files
        run: |
          pwd
          ls -a

      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: List Files After Checkout
        run: |
          pwd
          ls -a

      - name: Using a Simple JS Actions
        id: greet # id is need for steps reference
        uses: actions/hello-world-javascript-action@v1.1 # actions is username/ hello-world-javascript-action is repo/ version to ref
        with:
          who-to-greet: "Leeroy Jenkins"

      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
