name: Open Github Issue
author: Lee Tann
description: Open a github issue

inputs:
  token:
    description: Github token
    required: true
  title:
    description: Issue Title
    required: true
  body:
    description: Issue Body
    required: false
  assignees:
    description: Issue assignees
    required: false

outputs:
  issue_details:
    description: "The issue object as a json string"

runs:
  using: node12
  main: "dist/index.js"
